// GENERATED by scripts/gen-wordmarks.py — do not edit by hand.
// figlet face: smblock. Every row is padded to the wordmark's full width.

export type Wordmark = { text: string; cols: number; rows: string[] }

export const WORDMARKS = {
  missionControl: { text: "MISSION CONTROL", cols: 41, rows: [
    "▙▗▌▜▘▞▀▖▞▀▖▜▘▞▀▖▙ ▌ ▞▀▖▞▀▖▙ ▌▀▛▘▛▀▖▞▀▖▌  ",
    "▌▘▌▐ ▚▄ ▚▄ ▐ ▌ ▌▌▌▌ ▌  ▌ ▌▌▌▌ ▌ ▙▄▘▌ ▌▌  ",
    "▌ ▌▐ ▖ ▌▖ ▌▐ ▌ ▌▌▝▌ ▌ ▖▌ ▌▌▝▌ ▌ ▌▚ ▌ ▌▌  ",
    "▘ ▘▀▘▝▀ ▝▀ ▀▘▝▀ ▘ ▘ ▝▀ ▝▀ ▘ ▘ ▘ ▘ ▘▝▀ ▀▀▘",
  ] },
  needsYou: { text: "NEEDS YOU", cols: 25, rows: [
    "▙ ▌▛▀▘▛▀▘▛▀▖▞▀▖ ▌ ▌▞▀▖▌ ▌",
    "▌▌▌▙▄ ▙▄ ▌ ▌▚▄  ▝▞ ▌ ▌▌ ▌",
    "▌▝▌▌  ▌  ▌ ▌▖ ▌  ▌ ▌ ▌▌ ▌",
    "▘ ▘▀▀▘▀▀▘▀▀ ▝▀   ▘ ▝▀ ▝▀ ",
  ] },
  broke: { text: "BROKE", cols: 15, rows: [
    "▛▀▖▛▀▖▞▀▖▌ ▌▛▀▘",
    "▙▄▘▙▄▘▌ ▌▙▞ ▙▄ ",
    "▌ ▌▌▚ ▌ ▌▌▝▖▌  ",
    "▀▀ ▘ ▘▝▀ ▘ ▘▀▀▘",
  ] },
  moved: { text: "MOVED", cols: 15, rows: [
    "▙▗▌▞▀▖▌ ▌▛▀▘▛▀▖",
    "▌▘▌▌ ▌▚▗▘▙▄ ▌ ▌",
    "▌ ▌▌ ▌▝▞ ▌  ▌ ▌",
    "▘ ▘▝▀  ▘ ▀▀▘▀▀ ",
  ] },
} satisfies Record<string, Wordmark>

export type WordmarkId = keyof typeof WORDMARKS
