#!/usr/bin/env python3
"""Pre-render the figlet wordmarks Mission Control ships as static strings.

Writes lib/wordmarks.ts. Rendering happens here, once, so the app carries no
figlet dependency and every wordmark is byte-identical between server and
client renders.

Face: `smblock` (quadrant blocks, 4 rows). "MISSION CONTROL" is 41 columns,
so it fits a 360px phone at a legible size. Auditioned against future,
calvin_s, emboss2, pagga and small in the real fallback monospace: the
box-drawing faces render N as "ΠЧ" ("MEEDS YOU"); smblock is the only compact
face whose letters all read correctly.

Usage: python3 scripts/gen-wordmarks.py   (needs `pip install pyfiglet`)
"""
import json
import pathlib

import pyfiglet

FACE = 'smblock'
WORDS = {
    'missionControl': 'MISSION CONTROL',
    'needsYou': 'NEEDS YOU',
    'broke': 'BROKE',
    'moved': 'MOVED',
}


def render(text: str) -> list[str]:
    lines = [l.rstrip() for l in pyfiglet.figlet_format(text, font=FACE, width=300).split('\n')]
    while lines and not lines[-1].strip():
        lines.pop()
    while lines and not lines[0].strip():
        lines.pop(0)
    width = max(len(l) for l in lines)
    # Pad every row to the same width so a right-aligned or centred block stays rectangular.
    return [l.ljust(width) for l in lines]


out = [
    '// GENERATED by scripts/gen-wordmarks.py — do not edit by hand.',
    f'// figlet face: {FACE}. Every row is padded to the wordmark\'s full width.',
    '',
    'export type Wordmark = { text: string; cols: number; rows: string[] }',
    '',
    'export const WORDMARKS = {',
]
for key, text in WORDS.items():
    rows = render(text)
    out.append(f'  {key}: {{ text: {json.dumps(text)}, cols: {len(rows[0])}, rows: [')
    out.extend(f'    {json.dumps(r, ensure_ascii=False)},' for r in rows)
    out.append('  ] },')
out.append('} satisfies Record<string, Wordmark>')
out.append('')
out.append('export type WordmarkId = keyof typeof WORDMARKS')
out.append('')

target = pathlib.Path(__file__).resolve().parent.parent / 'lib' / 'wordmarks.ts'
target.write_text('\n'.join(out), encoding='utf-8')
print(f'wrote {target} ({len(WORDS)} wordmarks)')
